# Changes here will be overwritten by Copier
_commit: d56cb12
_src_path: https://github.com/python-project-templates/base.git
add_extension: python
email: t.paine154@gmail.com
github: 1kbgz
project_description: Minimum viable chat components
project_name: chatom
python_version_primary: '3.11'
team: the chatom authors
